name: PR Test

on: pull_request

permissions: read-all

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8  # v3
      - name: Set up Python
        uses: actions/setup-python@98f2ad02fd48d057ee3b4d4f66525b231c3e52b6  # v3
        with:
          python-version: "3.11-dev"
      - name: Set up Python
        uses: actions/setup-python@98f2ad02fd48d057ee3b4d4f66525b231c3e52b6  # v3
        with:
          python-version: "3.10"
      - name: Set up Python
        uses: actions/setup-python@98f2ad02fd48d057ee3b4d4f66525b231c3e52b6  # v3
        with:
          python-version: "3.9"
      - name: Set up Python
        uses: actions/setup-python@98f2ad02fd48d057ee3b4d4f66525b231c3e52b6  # v3
        with:
          python-version: "3.8"
      - name: Set up Python
        uses: actions/setup-python@98f2ad02fd48d057ee3b4d4f66525b231c3e52b6  # v3
        with:
          python-version: "3.7"
      - name: run UT
        run: |
          pip install tox
          tox