name: PR Test

on: pull_request

permissions: read-all

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608  # v3
      - name: Set up Python versions
        uses: actions/setup-python@65d7f2d534ac1bc67fcd62888c5f4f3d2cb2b236  # v4
        with:
          python-version: |
            3.7
            3.8
            3.9
            3.10
            3.11
            3.12-dev
      - name: run UT
        run: |
          pip install tox
          tox