name: PR Test

on: pull_request

permissions: read-all

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac  # v3
      - name: Set up Python versions
        uses: actions/setup-python@61a6322f88396a6271a6ee3565807d608ecaddd1  # v4
        with:
          python-version: |
            3.7
            3.8
            3.9
            3.10
            3.11
            3.12-dev
      - name: run UT
        run: |
          pip install tox
          tox