name: PR Test

on: pull_request

permissions:
  contents: read

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11  # v3
      - name: Set up Python versions
        uses: actions/setup-python@0a5c61591373683505ea898e09a3ea4f39ef2b9c  # v4
        with:
          python-version: |
            3.8
            3.9
            3.10
            3.11
            3.12
          allow-prereleases: true
      - name: run UT
        run: |
          pip install tox
          tox