name: Test and Optionally Publish
on:
  push:
    branches:
      - master
  pull_request:
    types:
      - opened
      - reopened
      - synchronize

permissions: read-all

jobs:
    test:
        name: Check code against linter/unit tests
        runs-on: ubuntu-latest
        strategy:
          matrix:
            python-version: ["3.7", "3.8", "3.9", "3.10", "3.11-dev"]
        steps:
        - uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b  # v3
        - name: Set up Python ${{ matrix.python-version }}
          uses: actions/setup-python@13ae5bb136fac2878aff31522b9efb785519f984  # v3
          with:
            python-version: ${{ matrix.python-version }}
        - name: Install dependencies
          run: python -m pip install tox tox-gh-actions
        - name: Test with Tox
          run: tox